jobs:
  build:
    steps:
      # 步骤 1: 检出代码（确保包含 package-lock.json）
      - uses: actions/checkout@v4

      # 步骤 2: 缓存 node_modules 和 package-lock.json
      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            node_modules
            package-lock.json  # 明确缓存 package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # 步骤 3: 仅在缓存未命中时安装依赖
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci  # 确保 package-lock.json 存在
